package com.dzmsoft.bazi.db.pojo;

public class BaziList {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column bazi_list.id
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column bazi_list.year
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    private String year;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column bazi_list.month
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    private String month;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column bazi_list.day
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    private String day;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column bazi_list.hour
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    private String hour;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column bazi_list.id
     * @return  the value of bazi_list.id
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column bazi_list.id
     * @param id  the value for bazi_list.id
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column bazi_list.year
     * @return  the value of bazi_list.year
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column bazi_list.year
     * @param year  the value for bazi_list.year
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column bazi_list.month
     * @return  the value of bazi_list.month
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column bazi_list.month
     * @param month  the value for bazi_list.month
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column bazi_list.day
     * @return  the value of bazi_list.day
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column bazi_list.day
     * @param day  the value for bazi_list.day
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column bazi_list.hour
     * @return  the value of bazi_list.hour
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public String getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column bazi_list.hour
     * @param hour  the value for bazi_list.hour
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    public void setHour(String hour) {
        this.hour = hour == null ? null : hour.trim();
    }
}