package com.dzmsoft.bazi.db.dao;

import com.dzmsoft.bazi.db.pojo.BaziList;
import com.dzmsoft.bazi.db.pojo.BaziListExample;
import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaziListMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int countByExample(BaziListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int deleteByExample(BaziListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int insert(BaziList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int insertSelective(BaziList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    List<BaziList> selectByExample(BaziListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    BaziList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") BaziList record,
            @Param("example") BaziListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int updateByExample(@Param("record") BaziList record, @Param("example") BaziListExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int updateByPrimaryKeySelective(BaziList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    int updateByPrimaryKey(BaziList record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table bazi_list
     * @mbggenerated  Sun Oct 30 13:14:58 CST 2016
     */
    PageList<BaziList> selectByExample(BaziListExample example, PageBounds pageBounds);

    /**
     * 产生编号
     * @param example
     * @return
     */
    String selectTopIndex(BaziListExample example);
}